import type { Farmer, Farm, FarmStats, Camera, Alert, WeeklyActivity, MonthlyReport, Subscription, Payment } from '../types';

export const mockFarmer: Farmer = {
  id: 'farmer-001',
  phone: '+242064000001',
  full_name: 'Mbemba Jean',
  first_name: 'Mbemba',
  country: 'CG',
  city: 'Brazzaville',
  whatsapp_number: '+242064000001',
  language: 'fr',
  created_at: '2025-01-15T08:00:00Z',
};

export const mockFarm: Farm = {
  id: 'farm-001',
  farmer_id: 'farmer-001',
  name: 'Ferme Mbemba',
  flock_type: 'broiler',
  current_count: 450,
  total_capacity: 600,
  location_city: 'Brazzaville',
  is_active: true,
};

export const mockFarmStats: FarmStats = {
  total_birds: 450,
  healthy_count: 401,
  monitored_count: 23,
  alerts_today: 2,
  health_score: 89,
  health_label: 'Excellent',
  mortality_rate: 0.4,
  stress_rate: 12,
  activity_rate: 94,
  last_sync_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
};

export const mockCameras: Camera[] = [
  {
    id: 'cam-001',
    farm_id: 'farm-001',
    name: 'Caméra 01',
    zone: 'Bâtiment A — Vue principale',
    status: 'online',
    last_seen_at: new Date(Date.now() - 30 * 1000).toISOString(),
    snapshot_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=640&q=80',
  },
  {
    id: 'cam-002',
    farm_id: 'farm-001',
    name: 'Caméra 02',
    zone: 'Bâtiment A — Zone élevage',
    status: 'online',
    last_seen_at: new Date(Date.now() - 45 * 1000).toISOString(),
    snapshot_url: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=640&q=80',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    farm_id: 'farm-001',
    camera_id: 'cam-002',
    camera_name: 'Caméra 02',
    alert_type: 'mortality',
    severity: 'critical',
    confidence: 94,
    description: '2 oiseaux immobiles détectés dans le secteur Nord-Est. Intervention recommandée.',
    advice: "L'IA a détecté 2 oiseaux sans mouvement depuis plus de 15 minutes. Il peut s'agir d'une mortalité ou d'une maladie grave.",
    immediate_steps: [
      'Isolez immédiatement les oiseaux concernés',
      'Observez plumes, yeux et fientes pour signes de maladie',
      'Si d\'autres oiseaux montrent les mêmes signes, appelez un vétérinaire',
      'Notez l\'heure et le nombre d\'oiseaux affectés',
    ],
    prevention_tip: 'Maintenez une bonne ventilation et évitez la surpopulation. Vérifiez la qualité de l\'eau et des aliments régulièrement.',
    snapshot_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=640&q=80',
    is_resolved: false,
    whatsapp_sent: true,
    created_at: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-002',
    farm_id: 'farm-001',
    camera_id: 'cam-001',
    camera_name: 'Caméra 01',
    alert_type: 'heat_stress',
    severity: 'warning',
    confidence: 87,
    description: '45% du troupeau regroupé sous les ventilateurs zone B. Température: 32°C.',
    advice: 'Un regroupement excessif sous les ventilateurs indique un stress thermique. Les oiseaux cherchent à se rafraîchir.',
    immediate_steps: [
      'Augmentez la vitesse des ventilateurs immédiatement',
      'Vérifiez et remplissez les abreuvoirs avec de l\'eau fraîche',
      'Réduisez la densité dans la zone B si possible',
      'Vaporisez de l\'eau sur le toit du bâtiment',
    ],
    prevention_tip: 'Installez un système d\'ombrage supplémentaire et programmez les repas aux heures fraîches (tôt le matin et en soirée).',
    snapshot_url: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=640&q=80',
    is_resolved: false,
    whatsapp_sent: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-003',
    farm_id: 'farm-001',
    camera_id: 'cam-001',
    camera_name: 'Caméra 01',
    alert_type: 'inactivity',
    severity: 'warning',
    confidence: 78,
    description: 'Oiseau inactif détecté en zone B pendant 20 minutes.',
    advice: "Un oiseau isolé et immobile peut être malade ou blessé. Une observation rapprochée est nécessaire.",
    immediate_steps: [
      'Localisez l\'oiseau en zone B',
      'Examinez visuellement l\'oiseau (posture, respiration)',
      'Isolez l\'oiseau si des symptômes sont visibles',
    ],
    prevention_tip: 'Des contrôles visuels quotidiens permettent de détecter les problèmes avant qu\'ils ne s\'aggravent.',
    snapshot_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=640&q=80',
    is_resolved: true,
    resolved_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    whatsapp_sent: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-004',
    farm_id: 'farm-001',
    camera_id: 'cam-002',
    camera_name: 'Caméra 02',
    alert_type: 'feeder_empty',
    severity: 'info',
    confidence: 96,
    description: 'La mangeoire de la zone Est semble vide depuis 30 minutes.',
    advice: "Les oiseaux cherchent de la nourriture sans en trouver. Cela peut entraîner du stress et des comportements agressifs.",
    immediate_steps: [
      'Remplissez la mangeoire de la zone Est',
      'Vérifiez le niveau des autres mangeoires',
      'Contrôlez le stock d\'aliments disponible',
    ],
    prevention_tip: 'Mettez en place un calendrier de remplissage régulier des mangeoires, deux fois par jour minimum.',
    snapshot_url: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=640&q=80',
    is_resolved: true,
    resolved_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    whatsapp_sent: false,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'alert-005',
    farm_id: 'farm-001',
    camera_id: 'cam-001',
    camera_name: 'Caméra 01',
    alert_type: 'abnormal_movement',
    severity: 'warning',
    confidence: 81,
    description: 'Mouvement anormal détecté dans la zone Ouest — agitation inhabituellement élevée.',
    advice: "Une agitation inhabituelle peut indiquer la présence d'un prédateur, une panique ou une baisse de qualité de l'air.",
    immediate_steps: [
      'Vérifiez l\'absence de prédateurs aux abords du bâtiment',
      'Contrôlez la ventilation et la qualité de l\'air',
      'Observez si l\'agitation se calme dans les 10 prochaines minutes',
    ],
    prevention_tip: 'Sécurisez le périmètre du poulailler avec un grillage adapté et vérifiez les filets de protection.',
    snapshot_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=640&q=80',
    is_resolved: false,
    whatsapp_sent: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockWeeklyActivity: WeeklyActivity[] = [
  { day: 'Lun', healthy: 398, monitored: 18 },
  { day: 'Mar', healthy: 402, monitored: 15 },
  { day: 'Mer', healthy: 395, monitored: 22 },
  { day: 'Jeu', healthy: 405, monitored: 12 },
  { day: 'Ven', healthy: 400, monitored: 20 },
  { day: 'Sam', healthy: 403, monitored: 19 },
  { day: 'Dim', healthy: 401, monitored: 23 },
];

export const mockReports: MonthlyReport[] = [
  {
    id: 'report-001',
    farm_id: 'farm-001',
    month: '2026-06',
    month_label: 'Juin 2026',
    mortality_rate: 0.8,
    alert_count: 7,
    health_score_avg: 91,
    avg_bird_count: 448,
    trend: 'up',
    generated_at: new Date().toISOString(),
  },
  {
    id: 'report-002',
    farm_id: 'farm-001',
    month: '2026-05',
    month_label: 'Mai 2026',
    mortality_rate: 1.2,
    alert_count: 12,
    health_score_avg: 88,
    avg_bird_count: 455,
    trend: 'stable',
    generated_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'report-003',
    farm_id: 'farm-001',
    month: '2026-04',
    month_label: 'Avril 2026',
    mortality_rate: 0.9,
    alert_count: 9,
    health_score_avg: 90,
    avg_bird_count: 460,
    trend: 'stable',
    generated_at: '2026-05-01T08:00:00Z',
  },
  {
    id: 'report-004',
    farm_id: 'farm-001',
    month: '2026-03',
    month_label: 'Mars 2026',
    mortality_rate: 1.5,
    alert_count: 15,
    health_score_avg: 85,
    avg_bird_count: 462,
    trend: 'down',
    generated_at: '2026-04-01T08:00:00Z',
  },
];

export const mockSubscription: Subscription = {
  id: 'sub-001',
  farmer_id: 'farmer-001',
  plan: 'eleveur',
  status: 'active',
  max_cameras: 3,
  price_fcfa: 5000,
  addon_cameras: 0,
  history_days: 90,
  started_at: '2026-04-14T00:00:00Z',
  expires_at: '2026-07-14T00:00:00Z',
};

export const mockPayments: Payment[] = [
  {
    id: 'pay-001',
    amount_fcfa: 5000,
    method: 'mtn_momo',
    status: 'completed',
    paid_at: '2026-05-14T10:30:00Z',
  },
  {
    id: 'pay-002',
    amount_fcfa: 5000,
    method: 'orange_money',
    status: 'completed',
    paid_at: '2026-04-14T09:15:00Z',
  },
  {
    id: 'pay-003',
    amount_fcfa: 5000,
    method: 'mtn_momo',
    status: 'completed',
    paid_at: '2026-03-14T11:00:00Z',
  },
];
